import {readFileSync,writeFileSync} from 'node:fs';
import {loadArticles} from './content-audit.mjs';
import {baseline,topics} from './round7-audit.mjs';
const articles=loadArticles().filter(a=>a.data.status==='published'&&!a.data.noindex&&a.data.publishedAt<=new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Jakarta'}));
const images=JSON.parse(readFileSync('src/data/article-images.json','utf8'));
const safe=s=>String(s).replaceAll('|','\\|').replaceAll('\n',' ');
const link=a=>'['+a.data.title+']('+a.data.canonical+')';
let imageDoc='# Article image replacement\n\nThe single source of truth is src/data/article-images.json. ArticleVisual.astro reads the manifest; individual Markdown files do not embed the primary image. All current assets are original editorial SVG concepts, not customer project photography. The build does not regenerate or overwrite them.\n\n## Replace an image\n\n1. Obtain permission for the real photograph. Remove identifying client data unless publication is authorized.\n2. Add an optimized local WebP/AVIF/JPEG under public/media/articles/. Target a 2:1 crop and at most 350 KiB; preserve the important subject on mobile.\n3. Edit the matching manifest record: src, actual width/height, alt, caption, kind: photo, permissionConfirmed: true, and truthful provenance. Keep suggestedPhoto as the brief. Never label a concept as completed work.\n4. The component uses explicit dimensions, responsive sizing and eager loading for the hero. The 2:1 display canvas contains other ratios without cropping; use the recommended crop for a full composition.\n5. Run npm run verify and review desktop/mobile. OG social cards remain separate generated editorial graphics.\n\nFor alt text, describe the visible subject, material and decision illustrated. Do not assert an unverified client, location or installed project. Avoid repeating a city or service keyword purely for SEO.\n\n';
for(const a of articles){const v=images[a.id];imageDoc+='## '+link(a)+'\n\n| Field | Value |\n|---|---|\n| Current dummy asset | '+v.src+' |\n| Repository file | public'+v.src+' |\n| Suggested real photo | '+safe(v.suggestedPhoto)+' |\n| Recommended ratio | 2:1; current '+v.width+' × '+v.height+' |\n| Current alt | '+safe(v.alt)+' |\n| Replacement alt guidance | Describe the actual visible '+safe(topics.find(t=>t.id===a.data.topic).label.toLowerCase())+' subject and its relationship to this article’s decision; omit unsupported project claims. |\n\n';}
writeFileSync('docs/ARTICLE-IMAGE-REPLACEMENT.md',imageDoc.trimEnd()+'\n');
let audit='# Article cannibalization audit\n\nScope: '+articles.length+' published articles, including all 24 baseline IDs and 50 Round 7 additions. Editorial review outcome: **zero unresolved major intent collisions**. Automated checks also reject duplicate intent/title/WhatsApp text, excessive heading overlap, and substantial copied paragraphs. These indicators are safeguards, not proof of search-engine ranking outcomes.\n\nCommercial pages own transactional local intent. Articles address a specific decision, comparison, preparation task or usage scenario and link to the commercial owner. No duplicate city pages or unverified service pages were added.\n\n## Topic replacements before publication\n\nAlready-covered suggestions were retained in their existing owner rather than republished: kerf, CNC versus laser, MDF versus HMR, vendor selection, general motif choice, privacy/light, estimating costs and quotation data. The new set instead covers export packaging, open curves, fastener coordination, surface orientation, service access, CNC pocket references, stair/bordes rhythm, partial replacement and workshop preparation.\n\nClose boundaries checked: shadow observation versus general tropical facade design; circulation versus partition privacy; railing appearance versus structural safety; visit preparation versus vendor selection; sponsorship-free cultural reference approval versus general Siger inspiration; local sample comparison versus general production sampling. Cross-links are deliberate continuations, not competing transactional landing pages.\n\n';
for(const a of articles){const d=a.data;audit+='## '+link(a)+'\n\n| Gate | Accepted boundary |\n|---|---|\n| Cohort / topic | '+(baseline.includes(a.id)?'Existing':'New')+' / '+d.topic+' |\n| Primary intent | '+safe(d.primaryIntent)+' |\n| Target reader | '+safe(d.targetUser)+' |\n| Keyword family | '+safe(d.targetKeywordCluster)+' |\n| Unique value | '+safe(d.uniqueValue)+' |\n| Closest overlap and boundary | '+safe(d.cannibalizationRisk)+' |\n| Commercial owner | '+d.relatedServices.map(s=>'['+s+'](https://cuttinglaserlampung.com/'+s+'/)').join('<br>')+' |\n| Related reading reviewed | '+d.relatedArticles.map(id=>'['+id+'](https://cuttinglaserlampung.com/artikel/'+id+'/)').join('<br>')+' |\n| Decision | Retain; no unresolved major collision identified |\n\n';}
writeFileSync('reports/ARTICLE-CANNIBALIZATION-AUDIT.md',audit.trimEnd()+'\n');
const serviceIds=[...readFileSync('src/data/services.ts','utf8').matchAll(/slug: '([^']+)'/g)].map(m=>m[1]);
const priorityIds=['vector-vs-bitmap-untuk-cutting','panel-besi-baut-atau-las','arah-serat-stainless-antarpanel','lubang-dudukan-acrylic','akses-servis-di-balik-panel-acp','panel-hmr-dekat-area-lembap','uji-kecocokan-spons-untuk-produk','sudut-dalam-cnc-dan-bentuk-pasangan','panel-pagar-akses-meter-dan-kotak-surat','bayangan-panel-pada-jam-berbeda','partisi-dan-jalur-sirkulasi','mockup-railing-dari-sudut-pandang-pengguna','persetujuan-referensi-budaya-untuk-panel','template-penempatan-huruf-pada-dinding','penamaan-komponen-dan-daftar-panel','menyiapkan-kunjungan-workshop-lampung','laser-cutting-vs-cnc-router','pvc-bukan-bahan-untuk-laser','menyiapkan-data-penawaran-fabrikasi'];
let indexing='# Indexing priority\n\nSubmit the production [sitemap](https://cuttinglaserlampung.com/sitemap.xml) after deployment is verified. Priorities guide monitoring, not ranking promises. Do not request manual indexing for every article at once. Inspect a few representative URLs if coverage does not develop normally; investigate crawl or quality issues before repeating requests.\n\n## Priority 1 — commercial service owners\n\n'+serviceIds.map(s=>'- ['+s+'](https://cuttinglaserlampung.com/'+s+'/)').join('\n')+'\n\n## Priority 2 — decision-rich supporting articles\n\nOne useful guide per topic plus existing process, safety and quotation anchors.\n\n'+priorityIds.map(id=>'- '+link(articles.find(a=>a.id===id))).join('\n')+'\n\n## Priority 3 — remaining useful informational articles\n\n'+articles.filter(a=>!priorityIds.includes(a.id)).map(a=>'- '+link(a)).join('\n')+'\n\nThe homepage, article hub, portfolio, contact, file guide and FAQ remain crawlable supporting navigation. Monitor their existing coverage alongside the service owners. No thin category routes were introduced.\n';
writeFileSync('reports/INDEXING-PRIORITY.md',indexing);
console.log('Round 7 editorial reports updated: 74 image briefs, intent boundaries and indexing priorities.');
